import { TuViChartData } from "./types";
import { TRADITIONAL_PALACE_LAYOUT } from "./constants";

// Sample data đầy đủ 12 cung chức để kiểm thử trực quan giao diện SVG renderer
// LƯU Ý: Dữ liệu mẫu này chỉ dùng để kiểm tra hiển thị UI/UX, không thay thế thuật toán tính toán thực tế.
export const sampleTuViChart: TuViChartData = {
  user: {
    name: "Ngô Đức Phong",
    gender: "Nam",
    solarDate: "20/03/2001",
    lunarDate: "26/02/2001",
    birthHour: "giờ Giáp Thìn (07:30)",
    stemsBranches: {
      year: "Tân Tỵ",
      month: "Tân Mão",
      day: "Nhâm Ngọ",
      hour: "Giáp Thìn",
    },
    cuc: "Mộc tam cục",
    menh: "Bạch Lạp Kim (Vàng chân đèn)",
    amDuong: "Âm Nam (Âm Dương thuận lý)",
    menhKhacCuc: "Mệnh Kim khắc Cục Mộc (-2)",
    camTinh: "Con rắn tướng tinh con thỏ",
    chuMenh: "Vũ Khúc",
    chuThan: "Thiên Cơ",
    conNha: "Con nhà BẠCH ĐẾ (trường thành)",
    doMang: "Ông Quan Đế độ mạng",
    canLuong: "4 lượng 0 chỉ",
    hanNam: "Bính Ngọ (2026)",
    lapLuc: "10:32 phút, ngày 26/04/2026",
    diemLaSo: 78,
    matrixScores: {
      "Mệnh": 1.7,
      "Phụ mẫu": 6.7,
      "Phúc đức": 3.6,
      "Điền trạch": 0,
      "Quan lộc": -8,
      "Nô bộc": -10,
      "Thiên di": -7,
      "Tật ách": 10,
      "Tài bạch": 3.3,
      "Tử tức": 12.4,
      "Thu thê": 14.4,
      "Huynh đệ": -1,
      "Mệnh Khắc Cục": -2,
      "Âm Dương thuận lý": 1.5,
    },
  },
  palaces: [
    // 1. Cung Thiên Di (Tỵ - Hàng 1, Cột 0)
    {
      id: "Tỵ",
      name: "THIÊN DI",
      branch: "Tỵ",
      stemBranchTag: "-Q. Tỵ",
      earthlyBranch: "Tỵ",
      majorStars: [
        { name: "VŨ KHÚC", brightness: "H", category: "main", nguHanh: "Kim" },
        { name: "PHÁ QUÂN", brightness: "H", category: "main", nguHanh: "Thủy" },
      ],
      auspiciousStars: [
        { name: "Tả phù", category: "auspicious" },
        { name: "Quốc ấn", category: "auspicious" },
        { name: "Thiên phúc", category: "auspicious" },
        { name: "Phương các", category: "auspicious" },
        { name: "Giải thần", category: "auspicious" },
        { name: "Lộc Tồn", category: "auspicious" },
      ],
      inauspiciousStars: [
        { name: "Thái tuế", category: "inauspicious" },
        { name: "Tướng quân", category: "inauspicious" },
      ],
      otherStars: [],
      transformations: {
        loc: "Tử tức",
        quyen: "Huynh đệ",
        khoa: "Tài bạch",
        ky: "Phu thê",
      },
      ageRange: 63,
      lifeStage: "Bệnh",
      annualStemBranch: "Năm Mão",
      monthNumber: 7,
      triet: true,
      gridCol: TRADITIONAL_PALACE_LAYOUT["Tỵ"].col,
      gridRow: TRADITIONAL_PALACE_LAYOUT["Tỵ"].row,
      pastelBgColor: TRADITIONAL_PALACE_LAYOUT["Tỵ"].pastelBg,
    },

    // 2. Cung Tật Ách (Ngọ - Hàng 1, Cột 1)
    {
      id: "Ngọ",
      name: "TẬT ÁCH",
      branch: "Ngọ",
      stemBranchTag: "+G. Ngọ",
      earthlyBranch: "Ngọ",
      majorStars: [
        { name: "THÁI DƯƠNG", brightness: "M", category: "main", nguHanh: "Hỏa" },
      ],
      auspiciousStars: [
        { name: "Văn xương", category: "auspicious" },
        { name: "Phong cáo", category: "auspicious" },
        { name: "Thiên khôi", category: "auspicious" },
        { name: "Thiên trù", category: "auspicious" },
        { name: "Đào hoa", category: "auspicious" },
        { name: "Thiếu dương", category: "auspicious" },
        { name: "Hóa quyền", category: "transformation" },
        { name: "Ân quang", category: "auspicious" },
        { name: "Tam thai", category: "auspicious" },
      ],
      inauspiciousStars: [
        { name: "Thiên sứ", category: "inauspicious" },
        { name: "Thiên không", category: "inauspicious" },
        { name: "Tiểu hao", category: "inauspicious" },
        { name: "Hóa kỵ", category: "inauspicious" },
        { name: "L.Thái Tuế", category: "annual" },
        { name: "L.Kình Dương", category: "annual" },
      ],
      otherStars: [],
      transformations: {
        loc: "Phúc đức",
        quyen: "Thiên di",
        khoa: "Thiên di",
        isTuKy: true,
      },
      ageRange: 53,
      lifeStage: "Suy",
      annualStemBranch: "Năm Thìn",
      monthNumber: 8,
      gridCol: TRADITIONAL_PALACE_LAYOUT["Ngọ"].col,
      gridRow: TRADITIONAL_PALACE_LAYOUT["Ngọ"].row,
      pastelBgColor: TRADITIONAL_PALACE_LAYOUT["Ngọ"].pastelBg,
    },

    // 3. Cung Tài Bạch (Mùi - Hàng 1, Cột 2)
    {
      id: "Mùi",
      name: "TÀI BẠCH",
      branch: "Mùi",
      stemBranchTag: "-Ấ. Mùi",
      earthlyBranch: "Mùi",
      isThan: true,
      majorStars: [
        { name: "THIÊN PHỦ", brightness: "Đ", category: "main", nguHanh: "Thổ" },
      ],
      auspiciousStars: [
        { name: "Thanh long", category: "auspicious" },
      ],
      inauspiciousStars: [
        { name: "Địa không", category: "inauspicious" },
        { name: "Tang môn", category: "inauspicious" },
      ],
      otherStars: [],
      transformations: {
        loc: "Tử tức",
        quyen: "Phụ mẫu",
        khoa: "Phu thê",
        ky: "Tử tức",
      },
      ageRange: 43,
      lifeStage: "Đế vượng",
      annualStemBranch: "Năm Tỵ",
      monthNumber: 9,
      gridCol: TRADITIONAL_PALACE_LAYOUT["Mùi"].col,
      gridRow: TRADITIONAL_PALACE_LAYOUT["Mùi"].row,
      pastelBgColor: TRADITIONAL_PALACE_LAYOUT["Mùi"].pastelBg,
    },

    // 4. Cung Tử Tức (Thân - Hàng 1, Cột 3)
    {
      id: "Thân",
      name: "TỬ TỨC",
      branch: "Thân",
      stemBranchTag: "+B. Thân",
      earthlyBranch: "Thân",
      majorStars: [
        { name: "THIÊN CƠ", brightness: "V", category: "main", nguHanh: "Mộc" },
        { name: "THÁI ÂM", brightness: "V", category: "main", nguHanh: "Thủy" },
      ],
      auspiciousStars: [
        { name: "Văn khúc", category: "auspicious" },
        { name: "Địa giải", category: "auspicious" },
        { name: "Thiếu âm", category: "auspicious" },
        { name: "Lực sĩ", category: "auspicious" },
        { name: "Hóa khoa", category: "transformation" },
        { name: "Thiên quý", category: "auspicious" },
        { name: "Bát tọa", category: "auspicious" },
      ],
      inauspiciousStars: [
        { name: "Đà la", category: "inauspicious" },
        { name: "Cô thần", category: "inauspicious" },
        { name: "Đẩu quân", category: "inauspicious" },
        { name: "L.Tang Môn", category: "annual" },
      ],
      otherStars: [],
      transformations: {
        loc: "Nô bộc",
        isTuQuyen: true,
        khoa: "Tật ách",
        ky: "Phúc đức",
      },
      ageRange: 33,
      lifeStage: "Lâm quan",
      annualStemBranch: "Năm Ngọ",
      monthNumber: 10,
      tuan: true,
      gridCol: TRADITIONAL_PALACE_LAYOUT["Thân"].col,
      gridRow: TRADITIONAL_PALACE_LAYOUT["Thân"].row,
      pastelBgColor: TRADITIONAL_PALACE_LAYOUT["Thân"].pastelBg,
    },

    // 5. Cung Nô Bộc (Thìn - Hàng 2, Cột 0)
    {
      id: "Thìn",
      name: "NÔ BỘC",
      branch: "Thìn",
      stemBranchTag: "+N. Thìn",
      earthlyBranch: "Thìn",
      majorStars: [
        { name: "THIÊN ĐỒNG", brightness: "H", category: "main", nguHanh: "Thủy" },
      ],
      auspiciousStars: [
        { name: "Thiên hỷ", category: "auspicious" },
        { name: "Tấu thư", category: "auspicious" },
        { name: "Thiên tài", category: "auspicious" },
      ],
      inauspiciousStars: [
        { name: "Quả tú", category: "inauspicious" },
        { name: "Trực phù", category: "inauspicious" },
        { name: "Thiên thương", category: "inauspicious" },
        { name: "Thiên la", category: "inauspicious" },
        { name: "L.Đà La", category: "annual" },
      ],
      otherStars: [],
      transformations: {
        loc: "Phụ mẫu",
        quyen: "Phu thê",
        khoa: "Tài bạch",
        ky: "Thiên di",
      },
      ageRange: 73,
      lifeStage: "Tử",
      annualStemBranch: "Năm Dần",
      monthNumber: 6,
      triet: true,
      gridCol: TRADITIONAL_PALACE_LAYOUT["Thìn"].col,
      gridRow: TRADITIONAL_PALACE_LAYOUT["Thìn"].row,
      pastelBgColor: TRADITIONAL_PALACE_LAYOUT["Thìn"].pastelBg,
    },

    // 6. Cung Phu Thê (Dậu - Hàng 2, Cột 3)
    {
      id: "Dậu",
      name: "PHU THÊ",
      branch: "Dậu",
      stemBranchTag: "-Đ. Dậu",
      earthlyBranch: "Dậu",
      majorStars: [
        { name: "TỬ VI", brightness: "V", category: "main", nguHanh: "Thổ" },
        { name: "THAM LANG", brightness: "V", category: "main", nguHanh: "Thủy" },
      ],
      auspiciousStars: [
        { name: "Hữu bật", category: "auspicious" },
        { name: "Thiên giải", category: "auspicious" },
        { name: "Lộc tồn", category: "auspicious" },
        { name: "Thiên quan", category: "auspicious" },
        { name: "Long trì", category: "auspicious" },
        { name: "Bác sĩ", category: "auspicious" },
      ],
      inauspiciousStars: [
        { name: "Phá toái", category: "inauspicious" },
        { name: "Quan phù", category: "inauspicious" },
      ],
      otherStars: [],
      transformations: {
        loc: "Tử tức",
        quyen: "Nô bộc",
        khoa: "Tử tức",
        ky: "Huynh đệ",
      },
      ageRange: 23,
      lifeStage: "Quan đới",
      annualStemBranch: "Năm Mùi",
      monthNumber: 11,
      tuan: true,
      gridCol: TRADITIONAL_PALACE_LAYOUT["Dậu"].col,
      gridRow: TRADITIONAL_PALACE_LAYOUT["Dậu"].row,
      pastelBgColor: TRADITIONAL_PALACE_LAYOUT["Dậu"].pastelBg,
    },

    // 7. Cung Quan Lộc (Mão - Hàng 3, Cột 0)
    {
      id: "Mão",
      name: "QUAN LỘC",
      branch: "Mão",
      stemBranchTag: "-T. Mão",
      earthlyBranch: "Mão",
      majorStars: [], // Vô chính diệu
      auspiciousStars: [],
      inauspiciousStars: [
        { name: "Địa kiếp", category: "inauspicious" },
        { name: "Lưu hà", category: "inauspicious" },
        { name: "Điều khách", category: "inauspicious" },
        { name: "Phi liêm", category: "inauspicious" },
      ],
      otherStars: [],
      transformations: {
        loc: "Huynh đệ",
        quyen: "Tật ách",
        khoa: "Tài bạch",
        ky: "Tật ách",
      },
      ageRange: 83,
      lifeStage: "Mộ",
      annualStemBranch: "Năm Sửu",
      monthNumber: 5,
      gridCol: TRADITIONAL_PALACE_LAYOUT["Mão"].col,
      gridRow: TRADITIONAL_PALACE_LAYOUT["Mão"].row,
      pastelBgColor: TRADITIONAL_PALACE_LAYOUT["Mão"].pastelBg,
    },

    // 8. Cung Huynh Đệ (Tuất - Hàng 3, Cột 3)
    {
      id: "Tuất",
      name: "HUYNH ĐỆ",
      branch: "Tuất",
      stemBranchTag: "+M. Tuất",
      earthlyBranch: "Tuất",
      majorStars: [
        { name: "CỰ MÔN", brightness: "H", category: "main", nguHanh: "Thủy" },
      ],
      auspiciousStars: [
        { name: "Thai phụ", category: "auspicious" },
        { name: "Nguyệt đức", category: "auspicious" },
        { name: "Hồng loan", category: "auspicious" },
        { name: "Hóa lộc", category: "transformation" },
      ],
      inauspiciousStars: [
        { name: "Thiên hình", category: "inauspicious" },
        { name: "Kình dương", category: "inauspicious" },
        { name: "Tử phù", category: "inauspicious" },
        { name: "Quan phủ", category: "inauspicious" },
        { name: "Địa võng", category: "inauspicious" },
      ],
      otherStars: [],
      transformations: {
        loc: "Phu thê",
        quyen: "Tử tức",
        khoa: "Phu thê",
        ky: "Tử tức",
      },
      ageRange: 13,
      lifeStage: "Mộc dục",
      annualStemBranch: "Năm Thân",
      monthNumber: 12,
      gridCol: TRADITIONAL_PALACE_LAYOUT["Tuất"].col,
      gridRow: TRADITIONAL_PALACE_LAYOUT["Tuất"].row,
      pastelBgColor: TRADITIONAL_PALACE_LAYOUT["Tuất"].pastelBg,
    },

    // 9. Cung Điền Trạch (Dần - Hàng 4, Cột 0)
    {
      id: "Dần",
      name: "ĐIỀN TRẠCH",
      branch: "Dần",
      stemBranchTag: "+C. Dần",
      earthlyBranch: "Dần",
      majorStars: [], // Vô chính diệu
      auspiciousStars: [
        { name: "Thiên y", category: "auspicious" },
        { name: "Đường phù", category: "auspicious" },
        { name: "Thiên việt", category: "auspicious" },
        { name: "Thiên đức", category: "auspicious" },
        { name: "Phúc đức", category: "auspicious" },
        { name: "Hỷ thần", category: "auspicious" },
      ],
      inauspiciousStars: [
        { name: "Thiên riêu", category: "inauspicious" },
        { name: "Kiếp sát", category: "inauspicious" },
        { name: "Linh tinh", category: "inauspicious" },
        { name: "L.Bạch Hổ", category: "annual" },
      ],
      otherStars: [],
      transformations: {
        loc: "Tật ách",
        quyen: "Thiên di",
        khoa: "Tử tức",
        ky: "Nô bộc",
      },
      ageRange: 93,
      lifeStage: "Tuyệt",
      annualStemBranch: "Năm Tý",
      monthNumber: 4,
      gridCol: TRADITIONAL_PALACE_LAYOUT["Dần"].col,
      gridRow: TRADITIONAL_PALACE_LAYOUT["Dần"].row,
      pastelBgColor: TRADITIONAL_PALACE_LAYOUT["Dần"].pastelBg,
    },

    // 10. Cung Phúc Đức (Sửu - Hàng 4, Cột 1)
    {
      id: "Sửu",
      name: "PHÚC ĐỨC",
      branch: "Sửu",
      stemBranchTag: "-T. Sửu",
      earthlyBranch: "Sửu",
      majorStars: [
        { name: "LIÊM TRINH", brightness: "Đ", category: "main", nguHanh: "Hỏa" },
        { name: "THẤT SÁT", brightness: "Đ", category: "main", nguHanh: "Kim" },
      ],
      auspiciousStars: [
        { name: "Hoa cái", category: "auspicious" },
      ],
      inauspiciousStars: [
        { name: "Thiên khốc", category: "inauspicious" },
        { name: "Bạch hổ", category: "inauspicious" },
        { name: "Bệnh phù", category: "inauspicious" },
      ],
      otherStars: [],
      transformations: {
        loc: "Huynh đệ",
        quyen: "Tật ách",
        khoa: "Tử tức",
        ky: "Tật ách",
      },
      ageRange: 103,
      lifeStage: "Thai",
      annualStemBranch: "Năm Hợi",
      monthNumber: 3,
      gridCol: TRADITIONAL_PALACE_LAYOUT["Sửu"].col,
      gridRow: TRADITIONAL_PALACE_LAYOUT["Sửu"].row,
      pastelBgColor: TRADITIONAL_PALACE_LAYOUT["Sửu"].pastelBg,
    },

    // 11. Cung Phụ Mẫu (Tý - Hàng 4, Cột 2)
    {
      id: "Tý",
      name: "PHỤ MẪU",
      branch: "Tý",
      stemBranchTag: "+C. Tý",
      earthlyBranch: "Tý",
      majorStars: [
        { name: "THIÊN LƯƠNG", brightness: "V", category: "main", nguHanh: "Thổ" },
      ],
      auspiciousStars: [
        { name: "Văn tinh", category: "auspicious" },
        { name: "Long đức", category: "auspicious" },
        { name: "Thiên thọ", category: "auspicious" },
      ],
      inauspiciousStars: [
        { name: "Đại hao", category: "inauspicious" },
        { name: "L.Thiên Khốc", category: "annual" },
        { name: "L.Thiên Hư", category: "annual" },
      ],
      otherStars: [],
      transformations: {
        loc: "Tật ách",
        quyen: "Thiên di",
        khoa: "Tử tức",
        ky: "Nô bộc",
      },
      ageRange: 113,
      lifeStage: "Dưỡng",
      annualStemBranch: "Năm Tuất",
      monthNumber: 2,
      gridCol: TRADITIONAL_PALACE_LAYOUT["Tý"].col,
      gridRow: TRADITIONAL_PALACE_LAYOUT["Tý"].row,
      pastelBgColor: TRADITIONAL_PALACE_LAYOUT["Tý"].pastelBg,
    },

    // 12. Cung Mệnh (Hợi - Hàng 4, Cột 3)
    {
      id: "Hợi",
      name: "MỆNH",
      branch: "Hợi",
      stemBranchTag: "-K. Hợi",
      earthlyBranch: "Hợi",
      majorStars: [
        { name: "THIÊN TƯỚNG", brightness: "V", category: "main", nguHanh: "Thủy" },
      ],
      auspiciousStars: [
        { name: "Thiên mã", category: "auspicious" },
      ],
      inauspiciousStars: [
        { name: "Thiên hư", category: "inauspicious" },
        { name: "Tuế phá", category: "inauspicious" },
        { name: "Phục binh", category: "inauspicious" },
        { name: "Hỏa tinh", category: "inauspicious" },
      ],
      otherStars: [],
      transformations: {
        loc: "Thiên di",
        quyen: "Phụ thê",
        khoa: "Phụ mẫu",
        ky: "Tử tức",
      },
      ageRange: 3,
      lifeStage: "Trường sinh",
      annualStemBranch: "Năm Dậu",
      monthNumber: 1,
      gridCol: TRADITIONAL_PALACE_LAYOUT["Hợi"].col,
      gridRow: TRADITIONAL_PALACE_LAYOUT["Hợi"].row,
      pastelBgColor: TRADITIONAL_PALACE_LAYOUT["Hợi"].pastelBg,
    },
  ],
};
